### ISSUE TITLE
Warping operation

### ISSUE THREAD

**Issue by ShengyuH** [DylanWusee/PointPWC#2]
hi Wenxuan, 
Thanks for making this work open-sourced. I have a couple of questions:

- How do you determine the #points at each stage? e.g, 8196 to 2048 to 512 to 256 to 64. And how do you determine the two neighborhood values? e.g, 32 and 16 respectively. I think these two sets of values are correlated and they together determine the receptive field, but can you help elaborate a little bit on it?

- In the paper you report that you warp the point clouds and then only estimate the residuals in the following steps. However, if I understand your codes correctly, you do use the warped point clouds to estimate the cost, but when estimating the new flow, you actually concatenate the estimated flow to the features and apply MLP on it. This is different from "estimating the residuals", you actually still estimate the full flow, though the previous motion information is contained in the upsampled flow and cost volume. Can you elaborate this choice?

- What does this scale value stand for here and how do you determine it? https://github.com/DylanWusee/PointPWC/blob/ff7d94205d9b519e30c5f6202adc65c5f9969fb7/models.py#L24.    Do you simply use it to align the magnitude of features?

Best,
Shengyu

**Comment by DylanWusee** [comment]
Hi Shengyu,

Thank you for your interest in our work. We will answer all your questions on the following:

- For the first question: the number of points and the neighborhood size are determined empirically. The parameter we use is actually our first attempt. We do conduct some experiments to find the best combination. And, it turns out our first choice is the best at this moment. Besides, We start from 8192 is because of the limited GPU memories and fair comparison with HPLFlowNet, which also use 8192 points as their input. 

- I think this is a misunderstanding of our paper. Maybe we should rephrase the warping layer part. We mainly introduce the intuition of using a warping layer. The goal of using a warping layer is to reduce the searching area and build a cost volume that contains only the residual flow information. In our paper, we also introduce the Scene Flow Predictor which takes the cost volume and the upsampled flow as input. The Scene flow predictor will do the "estimating the residuals" and also correct some potential errors in flow estimation. Basically, we try to make the network to learn a function that can estimate the residual flow and add to the full flow instead of do it by ourselves.

- Sorry for the confusion. The scale is just one of our fail attempts. You can just ignore it and set it to 1.0 . We will remove it in future updates.

Best,
Wenxuan
