### ISSUE TITLE
Wraping Layer

### ISSUE THREAD

**Issue by Hzj199** [DylanWusee/PointPWC#5]
Hi Wenxuan,
Thanks for making this work  open-sourced. I have a question:

In the paper you report that the warping layer is simply an element-wise addition as in Eq.(6). However, I noticed that there is interpolation operation in your codes. Can you elaborate it?

Best,
Zijun

**Comment by DylanWusee** [comment]
Hi There,

For warping on point clouds, it is indeed just a element-wise addition as in Eq.(6). The interpolation is just a cheaper way to compute flow 2 from flow 1 since we only predict flow 1. We could only warp with point cloud 2 and flow 2. A better way would be predict flow 1 and flow 2 at the same time.

Hope that helps.
Wenxuan
